### ISSUE TITLE
[Compat] Fails on Tessel 2

### ISSUE THREAD

**Issue by johnnyman727** [tessel/ble-ble113a#48]
Here is the output from trying to run the example:
```
INFO Looking for your Tessel...
INFO Connected to doorman.
INFO Building project.
INFO Writing project to RAM on doorman (149.504 kB)...
INFO Deployed.
INFO Running ble.js...
Trace: <Buffer ef bf bd 0c 00 00 01 00 02 00 02 00 5d 00 03 00 01 06>
    at e.parseIncomingPackets (/tmp/remote-script/node_modules/ble-ble113a/lib/messenger.js:1:7049)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Readable.push (_stream_readable.js:110:10)
    at null.<anonymous> (/usr/lib/node/tessel-export.js:229:24)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:411:10)
    at emitReadable (_stream_readable.js:405:7)
[Error: No existing response creator for packet of class 0 and command id 93]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Unable to connect to module.
    at Error (native)
    at e.<anonymous> (/tmp/remote-script/node_modules/ble-ble113a/lib/messenger.js:1:524)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

The first byte should be an `0x80` so there may be an issue with the UART peripheral in T2 firmware.

**Comment by rwaldron** [comment]
Wouldn't this be present in uses of UART? That is: if something was wrong with the firmware, wouldn't all messages be missing the first byte?

**Comment by johnnyman727** [comment]
@rwaldron My guess is that there might be some bug in the UART initialization code or some race condition. I'm just shooting in the dark here though.

**Comment by mbrevda** [comment]
were you able to take a closer look at this?

**Comment by johnnyman727** [comment]
@mbrevda no I haven't looked into this. I don't have a BLE module with me and I'll be traveling for the next several months.

**Comment by mbrevda** [comment]
Are you saying that besides for the month already waited there won't be a
resolution to this issue for the next few months?

**Comment by johnnyman727** [comment]
@mbrevda I'm saying that I won't be able to work on this for a few months but it is all open source if anyone else wants to investigate.

**Comment by johnnyman727** [comment]
You may want to just purchase a USB BLE dongle since it is so cheap and widely accessible.

**Comment by mbrevda** [comment]
It's been quite a few months, was there any progress made here?

**Comment by johnnyman727** [comment]
@mbrevda unfortunately, I don't think anyone is actively working on this. I'm happy to advise if you want to investigate yourself.
